import { STORYSHIP_CANONICALIZATION_POLICY, deepFreezeJson, hashCanonical } from './canonical.mjs';

const SCHEMAS = {
  constitution:'storyship/constitution-receipt/v0', source:'storyship/source-cut/v0', result:'storyship/result/v0',
  selector:'storyship/selector-receipt/v0', reserve:'storyship/reserve-receipt/v0', go:'storyship/launch-go/v0'
};
export const STORYSHIP_EVENT_TYPES = Object.freeze(['voyage-created','constitution-bound','source-bound','packet-sealed','generation-requested','generation-observed','encounter-recorded','selection-recorded','continuation-recorded','branch-composed','interpretation-recorded','residue-recorded','correction-recorded','customs-result-linked','checkpoint-sealed','voyage-stopped']);
export const STORYSHIP_RESULT_VALUES = Object.freeze(['supports','refuses','unresolved']);
export const STORYSHIP_RESULT_TARGETS = Object.freeze(['passenger_claim','lineage_claim','source_binding','packet_mapping','observation_method','selection_abstraction','continuity_law','destination_admission']);
export const STORYSHIP_FORBIDDEN_BERTH_CLASSES = Object.freeze(['missing raw evidence','inaccessible source','protected silence','explicit refusal','known prohibition','forgotten metadata','unresolved branch ownership']);
const SHA1=/^[0-9a-f]{40}$/; const SHA256=/^sha256:[0-9a-f]{64}$/;
function fail(code,msg){const e=new TypeError(msg);e.code=code;throw e;} function str(v,l){if(typeof v!=='string'||!v.trim())fail('INVALID_STORYSHIP_CONTRACT',`${l} must be non-empty`);return v;}
function arr(v,l){if(!Array.isArray(v))fail('INVALID_STORYSHIP_CONTRACT',`${l} must be array`);return v.map((x,i)=>str(x,`${l}[${i}]`));}
function exact(o,keys,l){if(!o||typeof o!=='object'||Array.isArray(o))fail('INVALID_STORYSHIP_CONTRACT',`${l} must be object`);const got=Object.keys(o);if(got.length!==keys.length||got.some(k=>!keys.includes(k)))fail('INVALID_STORYSHIP_CONTRACT',`${l} keys invalid`);}
function idRecord(schema, body, idKey){return deepFreezeJson({...body,[idKey]:hashCanonical(body)});}
export function createConstitutionReceipt(input){exact(input,['owner_repository','owner_head_sha','ordered_constitutive_paths','blob_sha_for_each_path'],'constitution input');str(input.owner_repository,'owner_repository');if(!SHA1.test(input.owner_head_sha))fail('INVALID_STORYSHIP_CONSTITUTION','owner_head_sha invalid');const paths=arr(input.ordered_constitutive_paths,'ordered_constitutive_paths');if(!paths.length||new Set(paths).size!==paths.length)fail('INVALID_STORYSHIP_CONSTITUTION','constitutive paths invalid');const pairs=paths.map(path=>{const blob=input.blob_sha_for_each_path?.[path];if(!SHA1.test(blob||''))fail('INVALID_STORYSHIP_CONSTITUTION','blob invalid');return {path,blob_sha:blob};});return deepFreezeJson({schema:SCHEMAS.constitution,canonicalization_policy:STORYSHIP_CANONICALIZATION_POLICY,owner_repository:input.owner_repository,owner_head_sha:input.owner_head_sha,ordered_constitutive_paths:paths,blob_sha_for_each_path:Object.fromEntries(pairs.map(x=>[x.path,x.blob_sha])),constitution_id:hashCanonical(pairs)});}
export function validateConstitutionReceipt(r){const expected=createConstitutionReceipt({owner_repository:r.owner_repository,owner_head_sha:r.owner_head_sha,ordered_constitutive_paths:r.ordered_constitutive_paths,blob_sha_for_each_path:r.blob_sha_for_each_path});if(r.schema!==SCHEMAS.constitution||r.canonicalization_policy!==STORYSHIP_CANONICALIZATION_POLICY||r.constitution_id!==expected.constitution_id)fail('INVALID_STORYSHIP_CONSTITUTION','constitution receipt invalid');return true;}
export function admitSourceCut(input){exact(input,['owning_world','stable_locator','revision_or_provider_identity','content_digest_when_available','acquisition_time','availability_status','evidence_class'],'source cut');['owning_world','stable_locator','revision_or_provider_identity','acquisition_time','availability_status','evidence_class'].forEach(k=>str(input[k],k));if(input.content_digest_when_available!==null&&!SHA256.test(input.content_digest_when_available))fail('INVALID_STORYSHIP_SOURCE_CUT','digest invalid');const body={schema:SCHEMAS.source,...input};return idRecord(SCHEMAS.source,body,'source_cut_id');}
export function validateSourceCut(r){const expected=admitSourceCut({owning_world:r.owning_world,stable_locator:r.stable_locator,revision_or_provider_identity:r.revision_or_provider_identity,content_digest_when_available:r.content_digest_when_available,acquisition_time:r.acquisition_time,availability_status:r.availability_status,evidence_class:r.evidence_class});if(r.schema!==SCHEMAS.source||r.source_cut_id!==expected.source_cut_id)fail('INVALID_STORYSHIP_SOURCE_CUT','source cut invalid');return true;}
export function createStoryshipResult(input){if(!STORYSHIP_RESULT_VALUES.includes(input.result)||!STORYSHIP_RESULT_TARGETS.includes(input.target))fail('INVALID_STORYSHIP_RESULT','result invalid');const body={schema:SCHEMAS.result,result:input.result,target:input.target,basis_event_ids:arr(input.basis_event_ids,'basis_event_ids'),reason_codes:arr(input.reason_codes,'reason_codes'),authority:'machine-test-only',owner_gate_status:'not-constituted'};return idRecord(SCHEMAS.result,body,'result_id');}
export function validateStoryshipResult(r){const e=createStoryshipResult(r);if(r.result_id!==e.result_id||r.authority!=='machine-test-only'||r.owner_gate_status!=='not-constituted')fail('INVALID_STORYSHIP_RESULT','result invalid');return true;}
export function createSelectorReceipt(input){if(!['recovered','partial','unresolved'].includes(input.recovery_status))fail('INVALID_SELECTOR','recovery status invalid');const evidence=arr(input.evidence_refs,'evidence_refs');if(input.recovery_status==='recovered'&&!evidence.length)fail('INVALID_SELECTOR','recovered selector requires evidence');const body={schema:SCHEMAS.selector,mechanism_id:str(input.mechanism_id,'mechanism_id'),recovery_status:input.recovery_status,evidence_refs:evidence,operator_inputs_visible:arr(input.operator_inputs_visible,'operator_inputs_visible'),allowed_outcomes:arr(input.allowed_outcomes,'allowed_outcomes'),non_selected_treatment:str(input.non_selected_treatment,'non_selected_treatment'),unresolved_notes:arr(input.unresolved_notes,'unresolved_notes')};return idRecord(SCHEMAS.selector,body,'selector_receipt_id');}
export function validateSelectorReceipt(r){const e=createSelectorReceipt(r);if(r.selector_receipt_id!==e.selector_receipt_id)fail('INVALID_SELECTOR','selector invalid');return true;}
export function createReserveReceipt(input){for(const k of ['observed_available_credits','protected_reserve_credits'])if(!Number.isInteger(input[k])||input[k]<0)fail('INVALID_RESERVE',`${k} invalid`);if(input.protected_reserve_credits>input.observed_available_credits)fail('INVALID_RESERVE','protected reserve exceeds available credits');const body={schema:SCHEMAS.reserve,observed_available_credits:input.observed_available_credits,protected_reserve_credits:input.protected_reserve_credits,spendable_credits:input.observed_available_credits-input.protected_reserve_credits,observed_at:str(input.observed_at,'observed_at'),basis_ref:str(input.basis_ref,'basis_ref')};return idRecord(SCHEMAS.reserve,body,'reserve_receipt_id');}
export function validateReserveReceipt(r){const e=createReserveReceipt(r);if(r.reserve_receipt_id!==e.reserve_receipt_id||r.spendable_credits!==e.spendable_credits)fail('INVALID_RESERVE','reserve invalid');return true;}
export function createLaunchGoReceipt(input){if(!SHA1.test(input.launch_candidate_head_sha||''))fail('INVALID_GO','head invalid');for(const k of ['packet_id','reserve_receipt_id','selector_receipt_id'])if(!SHA256.test(input[k]||''))fail('INVALID_GO',`${k} invalid`);const body={schema:SCHEMAS.go,launch_candidate_head_sha:input.launch_candidate_head_sha,packet_id:input.packet_id,reserve_receipt_id:input.reserve_receipt_id,selector_receipt_id:input.selector_receipt_id,approved_by:str(input.approved_by,'approved_by'),approved_at:str(input.approved_at,'approved_at')};return idRecord(SCHEMAS.go,body,'launch_go_id');}
export function validateLaunchGoReceipt(r){const e=createLaunchGoReceipt(r);if(r.launch_go_id!==e.launch_go_id)fail('INVALID_GO','go invalid');return true;}
