import { deepFreezeJson, hashCanonical } from './canonical.mjs';
import { STORYSHIP_EVENT_TYPES, validateConstitutionReceipt, validateSourceCut } from './contract.mjs';
const EVENT_SCHEMA='storyship/event/v0'; const SHA256=/^sha256:[0-9a-f]{64}$/;
function fail(code,msg){const e=new TypeError(msg);e.code=code;throw e;} function plain(v){return v&&typeof v==='object'&&!Array.isArray(v);}
function validateNarrative(items){if(!Array.isArray(items))fail('INVALID_STORYSHIP_EVENT','narrative must be array');for(const x of items){if(!plain(x)||Object.hasOwn(x,'replaces_reality_record_id'))fail('INVALID_STORYSHIP_EVENT','narrative cannot overwrite reality');}}
function validateArtifact(payload){if(!plain(payload)||!plain(payload.artifact))return;const {provider_identity,content_digest,artifact_id}=payload.artifact;if(!SHA256.test(content_digest||'')||artifact_id!==hashCanonical({provider_identity,content_digest}))fail('INVALID_STORYSHIP_EVENT','artifact identity invalid');}
export function createStoryshipEvent(input){if(!plain(input)||input.schema!==EVENT_SCHEMA)fail('INVALID_STORYSHIP_EVENT','event schema invalid');if(!Number.isInteger(input.event_seq)||input.event_seq<1)fail('INVALID_STORYSHIP_EVENT','event_seq invalid');if(!STORYSHIP_EVENT_TYPES.includes(input.event_type))fail('INVALID_STORYSHIP_EVENT','event_type invalid');if(!SHA256.test(input.constitution_id||''))fail('INVALID_STORYSHIP_EVENT','constitution_id invalid');if(!Array.isArray(input.source_cut))fail('INVALID_STORYSHIP_EVENT','source_cut invalid');for(const cut of input.source_cut)validateSourceCut(cut);validateNarrative(input.narrative_interpretations);if(input.event_type==='generation-observed')validateArtifact(input.payload);const body={...input,source_cut:[...input.source_cut].sort((a,b)=>a.source_cut_id.localeCompare(b.source_cut_id))};return deepFreezeJson({...body,event_id:hashCanonical(body)});}
export function validateStoryshipEvent(event){if(!plain(event)||!SHA256.test(event.event_id||''))fail('INVALID_STORYSHIP_EVENT','event id invalid');const {event_id,...body}=event;const expected=createStoryshipEvent(body);if(event_id!==expected.event_id)fail('INVALID_STORYSHIP_EVENT','event identity mismatch');return true;}
export function appendStoryshipEvent(events,input){if(!Array.isArray(events))fail('INVALID_STORYSHIP_LEDGER','events must be array');const expected=events.length+1;if(input.event_seq!==expected)fail('INVALID_STORYSHIP_LEDGER','event_seq must append contiguously');const event=createStoryshipEvent(input);if(events.length){const first=events[0];if(event.voyage_id!==first.voyage_id||event.constitution_id!==first.constitution_id)fail('INVALID_STORYSHIP_LEDGER','voyage/constitution mismatch');}return deepFreezeJson([...events,event]);}
export function verifyStoryshipLedger({constitution,events}){validateConstitutionReceipt(constitution);if(!Array.isArray(events)||!events.length)fail('INVALID_STORYSHIP_LEDGER','ledger must contain events');let voyage=null;for(let i=0;i<events.length;i++){const e=events[i];validateStoryshipEvent(e);if(e.event_seq!==i+1)fail('INVALID_STORYSHIP_LEDGER','sequence gap');if(e.constitution_id!==constitution.constitution_id)fail('INVALID_STORYSHIP_LEDGER','constitution mismatch');voyage??=e.voyage_id;if(e.voyage_id!==voyage)fail('INVALID_STORYSHIP_LEDGER','mixed voyage');}return deepFreezeJson({voyage_id:voyage,constitution_id:constitution.constitution_id,event_count:events.length,tip_event_id:events.at(-1).event_id});}
